name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
          
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls -l # Liste les fichier du répertoire courant
      - run: sudo apt install -y cowsay

      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt